version: '3'
services:
  java-srv:
    build:
      context: java-srv
    depends_on:
      - db-runner
    links:
      - "db:db"
    volumes:
      - ./log:/root/log

  db:
    image: cockroachdb/cockroach:v19.2.2
    ports:
     - "26257:26257"
     - "8080:8080"
    command: start-single-node --insecure

  db-runner:
    image: cockroachdb/cockroach:v19.2.2
    command:
      - shell
      - /usr/local/bin/init-data.sh
    volumes:
     - ./db/init-data.sh:/usr/local/bin/init-data.sh:ro
     - ./db/sql:/docker-entrypoint-initdb.d
    depends_on:
     - db
    links:
     - "db:db"
